### ISSUE TITLE
Is infinite scroll still available?

### ISSUE THREAD

**Issue by crbarnett** [digisavvy/some-like-it-neat#116]
Hello, trying to get infinite scroll enabled for the main blog page.
http://www.asalesguy.com/sales-blog/

Mentioned here, it sounds like it should work. https://github.com/digisavvy/some-like-it-neat#infinite-scroll-and-jetpack

"Requires that you have Jetpack installed and have configured the plugin to use Infinite Scroll."
I have jetpack enabled, but it is telling me under theme enhancements that infinite scroll isn't available. Screenshot of Jetpack options: https://imgur.com/a/Nibs8
![infinite](https://user-images.githubusercontent.com/916910/30616133-181cbbb6-9d46-11e7-8a27-e0d230a541e8.png)

"Additionally, you'll need to go into the Customizer to add theme support." 
I was not able to locate any particular options for infinite scroll from the Customizer menu option. Maybe this is because Jetpack hasn't registered the function to recognize it?

I do see on line 92 of the functions file, what appears to be the function to call Jetpack infinite scroll... hmmm.  Any ideas?

We're using Version: 1.3.8 of the theme
Thank you very much for any assistance.

**Comment by digisavvy** [comment]
Hey @crbarnett -
Thanks for writing in. So there's been a lot of updates since 1.3.8. But if you go to Customizer > General Site Content Settings > Content Extras you should see a setting there to enable Infinite Scroll. If it's not set to yes then you'll see that message. 

If you don't see that message, then it's possible it wasn't implemented by that point. 

If it interests you, the most recent version of the theme is on the development branch and is updated for Bourbon 5.0 and Neat 2.x
