### ISSUE TITLE
updated gulp - compiling to temp folder

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#122]
I've updated gulp on an old site but when I come to make changes it compiles out of the theme directory and into a temp folder on my computer. How do I change that?

Thanks

**Comment by digisavvy** [comment]
Hey there,
Sorry you're running into this issue. I should let you know that I've been working on a different version of this theme that uses webpack-mix instead of gulp. You should try that. The theme is much the same but uses Grid CSS instead of Neat (although Neat is still packaged). https://github.com/digisavvy/some-like-it-neat/tree/webpack-mix-config

**Comment by millo2k** [comment]
Great, I'll take a look thanks.

Any ideas how to sort this problem (its for an older version of somelikeitneat that needs some amends)

**Comment by digisavvy** [comment]
I'll have a look at it and see what's going on. I may have further questions for you.
