### ISSUE TITLE
CSS map

### ISSUE THREAD

**Issue by nelsonvassalo** [digisavvy/some-like-it-neat#62]
Hi!

I can't seem to get my minified CSS files to map out to the correspondent SCSS files, even when I'm debug mode in WP. Am I missing something in gulpfile.js?

Thanks!

**Comment by digisavvy** [comment]
Hey there,
Sorry you're having troubles with the theme. Just a note, CSS files are output to /assets/css - can you verify if you have any files there? Minified files are always output, so that's curious to me.

This is what the CSS folder should look like: 
![gulpfile_js_ _digisavvy_dev__somechild_dev__cultstorelocator_dev__innovationinmedtech_dev__somelikeitneat_dev__amla_dev__cultofindividuality_dev__gmuproject_dev__voyagevixens_dev__mobile_template__antaeus_dev__full_mobile_template_6slp9l0w_](https://cloud.githubusercontent.com/assets/984399/6467744/fc2ba1b4-c184-11e4-81c7-be6c9fba8a3a.png)

**Comment by nelsonvassalo** [comment]
yes, it's indeed giving me both expanded and minified versions in the /css folder but no source map.

**Comment by digisavvy** [comment]
By default, sourcemaps are disabled
![gulpfile_js_ _digisavvy_dev__somechild_dev__cultstorelocator_dev__innovationinmedtech_dev__somelikeitneat_dev__amla_dev__cultofindividuality_dev__gmuproject_dev__voyagevixens_dev__mobile_template__antaeus_dev__full_mobile_template_6slp9l0w_](https://cloud.githubusercontent.com/assets/984399/6468788/69c26aee-c18c-11e4-960f-af4b793100d0.png)
If you remove the highlighted area in the screenshot, then you should get them back. I'm looking to modify this so that sourcemaps are always generated. Right now, when generated, they break browsersync, causing the browser to refresh and not sync on style changes.
