### ISSUE TITLE
Flexnav menu mobile dropdown

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#63]
My test site: http://217.199.187.190/cliftonchildrenshouse.co.uk/

The menu is fine but when on mobile the touch dropdown keeps collapsing and doesnt stay open.

Any ideas?

Thanks

**Comment by digisavvy** [comment]
The config looks fine and I don't see any errors. The thing I'm noticing is that the menu seems to open on hover AND click. So when you hover then click, the menu is collapsing, so that's the nature of what you're seeing. If you just hover then the menu will open and won't collapse until you mouse-out.

That said, the config of the flexnav menu does look correct. There could be a style that is messing with things. You could also try to set hoverIntent to false, although I don't think it would help. Give it a go and lmk if that works or not.

**Comment by millo2k** [comment]
Thanks for getting back to me.

Your right, for some reason the drop down sub menu is adding the class 'flexnav-show' on hover in mobile! I have no idea why!

I have looked through the stylesheets. I have matched up your original with it but I can't see whats been changed to make this happen.

Any ideas where this kind of style would be found? (I've been looking high and low in components/flexnav).

Thanks
