### ISSUE TITLE
Project variable needs clarification or changes

### ISSUE THREAD

**Issue by jb510** [digisavvy/some-like-it-neat#64]
See: https://cloudup.com/c3AsFtBjVTb

It's not clear from the comment in gulpfile.js that "project" is the URL  used for browsersync.

Hence, I put in my theme name 9seeds2014.  So browser sync was looking for 9seeds2014.dev

Worse.  .dev is hard coded.  So, whereas mine is actually lcl.9seeds.com, it's just all wrong.  

Personally can just change this in my fork, no biggie.  However...  I think it's worth discussing options and at minimum

**Comment by digisavvy** [comment]
Hey JB,
Thanks for this! I would love a PR on the dev branch for this, if you'd be open for it.

You are right, hardcoding anything here isn't great. A variable for the project URL is ideal.

**Comment by jb510** [comment]
Dude you'er impatient....  5 more seconds and you'd see I did

**Comment by digisavvy** [comment]
Dude! I was writing my response and I saw  you referencing this. I was trying to watch funny cat vids and this notification came in thru slack.

**Comment by jb510** [comment]
Lesson learned.  Interrupting watching cat videos results in wasted time...  next time finish the cat videos first.

**Comment by jb510** [comment]
Note I do GitHub PR's wrong more often then right...  let me know if I screwed it up

**Comment by awroemanto** [comment]
I've just cloned the latest git and the .dev is not there in the browserSync.init and it works just fine
Anyway, @jb510  you should not use your theme name there, instead use the localhost development URL in it exactly like @digisavvy suggested above
For example because I use AMPPS in the development I use 
```
var project 	= '127.0.0.1/wp/',
```
in the var project (wp is my wordpress roots in AMPPS htdocs)
And in the gulp task browser sync should look like this
```
gulp.task('browser-sync', function() {
	var files = [
		'**/*.php'
	];
	browserSync.init(files, {
		proxy: project
	});
});
```
and then go to access browser-sync at
localhost:3001
to check in the proxying target
![screen shot 2015-03-18 at 6 15 25 pm](https://cloud.githubusercontent.com/assets/2385653/6707580/d2d39ef8-cd9a-11e4-95a7-e02994ef1af0.png)
After that you can access your browser-sync ready local environment in the http://localhost:3000/9seeds2014/
(if you set the var project with a correct local development URL)

**Comment by digisavvy** [comment]
Got this one completed. Thanks again for the input, JB.

**Comment by jb510** [comment]
@awroemanto I think there is some confusion.

The intent of this PR was to do to things.
1) Clarify that the project var is the PROJECT NAME, not a url
2) Explicitly define a browsersync URL

In your example you want to use my PR, and set the URL value to 0.0.0.0/wp/, that's your browser sync url.

'project' gets used elsewhere in the gulpfile (build, zip, etc...)

**Comment by jb510** [comment]
@digisavvy wait no, I review what you committed here https://github.com/digisavvy/some-like-it-neat/commit/5fdf798dbf169bb1f5368db0d28d476f82c7a198 and it doesn't split project and url things, it just removed  .dev, but that doesn't work for the broswersync url.  I think that's what caused the problem @awroemanto was having.

**Comment by awroemanto** [comment]
Thanks @jb510 I realize that yesterday I got confused with your first comment mistaking the PR with a question thats why I immediately delete my comment. But the things with browser-sync is fine now in my end.

**Comment by jb510** [comment]
Awesome! Glad we got it all worked out.
