### ISSUE TITLE
Just A Couple Of Things

### ISSUE THREAD

**Issue by ginblue** [digisavvy/some-like-it-neat#70]
Started building a them with SLIT today, and have run into a couple of issues (maybe I'm one of them).

Found and removed duplicate call for comments - template-right-col.php - line 45 (assuming this should not be there).

I cannot get a page with left sidebar to work. Made new page, used sidebar left template, but displaying page with right sidebar. Cant see where '_template-2col-r-sidebar.scss' gets picked up.

FlexNav jumping on page load. On page load the first  button appears about 30px from left page edge, then moves out to fill the gap. The movement is animated. If it is an expected behavior I don't know how to stop it.

Finally! More to do with Neat itself. The default Neat breakpoints (below _grid-settings.scss) appear to force a change in column numbers from 12 to 8.

$medium-screen-up: new-breakpoint(min-width $medium-screen 4);
$large-screen-up: new-breakpoint(min-width $large-screen 8); 

Not sure if this is illusory or is actually going to effect the layout. Just like to get your thoughts on the matter.

Am enjoying working with Some Like it Neat but its very different to what I'm used to Foundation, Pure, Bones). 

Thanks in advance Anthony

**Comment by digisavvy** [comment]
Hey Anthony,
Sorry about the delay here. Busy week!
You're spot on about the left sidebar issue in the left sidebar template. I went ahead and resolved that issue with the help of flexnav. =)

FlexNav jumping issue. That's more a problem with the script itself; I've resolved the issue which keeps it from happening, the problem is that when the menu collapses, it's no longer smooth. Can't seem to figure that one out just yet. I've been eye-balling some other accessible nav scripts as a potential replacement. Stay tuned there.

As for the breakpoints you noted. Those don't actually get used at all in SLiN. If you happen to use any of the patterns from http://refills.bourbon.io then those DO use those breakpoints. I added a comment to clarify. Thanks for asking and for the feedback.

**Comment by ginblue** [comment]
Hi Alex,
Thanks for the reply.

I often use SlickNav and will give a try in SLiN. Let you know how it goes.

Finding Neat breakpoints a little confusing for some reason, so thanks for  
clarifying that for me!

Keep up the good work, looking forward to seeing this framework develop.

Anthony

On Sat, 18 Apr 2015 22:12:36 +0100, Alex Vasquez  
<notifications@github.com> wrote:

>
> Hey Anthony,
> Sorry about the delay here. Busy week!
> You're spot on about the left sidebar issue in the left sidebar  
> template. I went ahead and resolved that issue with the help of flexnav.  
> =)
>
> FlexNav jumping issue. That's more a problem with the script itself;  
> I've resolved the issue which keeps it from happening, the problem >is  
> that when the menu collapses, it's no longer smooth. Can't seem to  
> figure that one out just yet. I've been eye-balling some other  
> >accessible nav scripts as a potential replacement. Stay tuned there.
>
> As for the breakpoints you noted. Those don't actually get used at all  
> in SLiN. If you happen to use any of the patterns from  
> http://>refills.bourbon.io then those DO use those breakpoints. I added  
> a comment to clarify. Thanks for asking and for the feedback.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Using Opera's mail client: http://www.opera.com/mail/
