### ISSUE TITLE
Add documentation for PHPCS

### ISSUE THREAD

**Issue by jeffreynolte** [digisavvy/some-like-it-neat#75]

**Comment by digisavvy** [comment]
You sound like my mom! ;-)

**Comment by jeffreynolte** [comment]
Ooof! That was harsh.  Haha

**Comment by digisavvy** [comment]
I do need to flesh this part out. One of the things I see is that folks will try to run gulp and it bombs out, due to PHPCS not available or found. Is there a reliable way to install "globally" and then set the path variable? I've only been able to do this when adding my specific theme directory to the $PATH variable. Just curious if you had any thoughts there. Thanks, ma. =)

**Comment by jeffreynolte** [comment]
We are using the theme on all the projects now along with Travis CI so figuring this out would be a big help for us since we can have our team reference the docs and setup rather than having the builds fail at TCI.   I know Udit has some experience with this, adding him in to the convo. 

cc/ @desaiuditd

**Comment by digisavvy** [comment]
Wow. That's pretty cool! =) Would love to see a site or two in the wild running it! 

But, yeah, if we can make the phpcs implementation a bit smoother, then that would be rad.
